import { Field } from "./utils/redux/reducers/formReducer"
export const initialFormState:Field[] = [
    {
        id:"0",
        type: "text",
        title: "Логин",
        variancy: [],
        conditionHide: {},
        conditionNotEditable:{},
        DefaultValue:"",
        Value:"admin",
    },
    {
        id:"1",
        type: "date",
        title: "Дата рождения",
        variancy: [],
        conditionHide: {},
        conditionNotEditable:{},
        DefaultValue:"",
        Value:"",
    },
    {
        id:"2",
        type: "checkbox",
        title: "Употребляете алкоголь",
        variancy: ["Да", "Нет"],
        conditionHide: {},
        conditionNotEditable:{id:"1", condition:(value: string)=>{return (new Date().getTime() - new Date(value).getTime()) / (24 * 3600 * 365.25 * 1000) < 18}},
        DefaultValue:"Нет",
        Value:"",
    },
    {
        id:"3",
        type: "checkbox",
        title: "образование",
        variancy: ["высшее", "среднее", "среднеспециальное"],
        conditionHide: {},
        conditionNotEditable:{},
        DefaultValue:"",
        Value:"",
    },
    {
        id:"4",
        type: "select",
        title: "служили в армии",
        variancy: ['да', "нет"],
        conditionHide: {},
        conditionNotEditable:{},
        DefaultValue:"",
        Value:"",
    },
    {
        id:"5",
        type: "select",
        title: "есть военный билет",
        variancy: ["да", "нет"],
        conditionHide: {},
        conditionNotEditable:{id:"4", condition:(value: string)=>{return value === "да"}},
        DefaultValue:"",
        Value:"",
    },
    
]
    
    // "8":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "9":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "10":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "11":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "12":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "13":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "14":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "15":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "16":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "17":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "18":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "19":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
    // "20":{
    //     type: "",
    //     title: "",
    //     variancy: [],
    //     conditionHide: {},
    //     conditionNotEditable:{},
    //     DefaultValue:"",
    //     Value:"",
    // },
