export const json = {
    "all_data": [
      {
        "id": 71156151,
        "title": "Word",
        "word": "apple",
        "paragraph": "Lorem ipsum",
        "translate": "яблоко",
      },
      {
        "id": 71156150,
        "title": "Word",
        "word": "apply",
        "paragraph": "Lorem ipsum",
        "translate": "принять",
      },
      {
        "id": 71156140,
        "title": "Word",
        "word": "can",
        "paragraph": "Lorem ipsum",
        "translate": "уметь",
      },
      {
        "id": 71156111,
        "title": "Word",
        "word": "buscket",
        "paragraph": "Lorem ipsum",
        "translate": "корзина",
      },
      {
        "id": 71156125,
        "title": "Word",
        "word": "multiply",
        "paragraph": "Lorem ipsum",
        "translate": "умножать",
      },
      {
        "id": 70056151,
        "title": "Word",
        "word": "approximatelly",
        "paragraph": "Lorem ipsum",
        "translate": "приблизительно",
      },
      {
        "id": 81156151,
        "title": "Word",
        "word": "appear",
        "paragraph": "Lorem ipsum",
        "translate": "появиться",
      },
      {
        "id": 71856151,
        "title": "Word",
        "word": "reach",
        "paragraph": "Lorem ipsum",
        "translate": "достичь",
      },
      {
        "id": 71186151,
        "title": "Word",
        "word": "burger",
        "paragraph": "Lorem ipsum",
        "translate": "бургер",
      },
      {
        "id": 71156851,
        "title": "Word",
        "word": "water",
        "paragraph": "Lorem ipsum",
        "translate": "вода",
      },
      {
        "id": 71156881,
        "title": "Word",
        "word": "melon",
        "paragraph": "Lorem ipsum",
        "translate": "дыня",
      },
      {
        "id": 71156211,
        "title": "Word",
        "word": "strike",
        "paragraph": "Lorem ipsum",
        "translate": "удар",
      },
      {
        "id": 71151451,
        "title": "Word",
        "word": "law",
        "paragraph": "Lorem ipsum",
        "translate": "закон",
      },
      {
        "id": 71056151,
        "title": "Word",
        "word": "function",
        "paragraph": "Lorem ipsum",
        "translate": "функция",
      },
      {
        "id": 70156151,
        "title": "Word",
        "word": "digit",
        "paragraph": "Lorem ipsum",
        "translate": "цифра",
      },
      {
        "id": 71156051,
        "title": "Word",
        "word": "sample",
        "paragraph": "Lorem ipsum",
        "translate": "образец",
      },
      {
        "id": 71156101,
        "title": "Word",
        "word": "letter",
        "paragraph": "Lorem ipsum",
        "translate": "буква",
      },
      {
        "id": 11156151,
        "title": "Word",
        "word": "flow",
        "paragraph": "Lorem ipsum",
        "translate": "поток",
      },
      {
        "id": 72156151,
        "title": "Word",
        "word": "standart",
        "paragraph": "Lorem ipsum",
        "translate": "средний",
      },
      {
        "id": 71356151,
        "title": "Word",
        "word": "scar",
        "paragraph": "Lorem ipsum",
        "translate": "шрам",
      },
      {
        "id": 711446151,
        "title": "Word",
        "word": "swear",
        "paragraph": "Lorem ipsum",
        "translate": "клятва",
      },
      {
        "id": 71157151,
        "title": "Word",
        "word": "hope",
        "paragraph": "Lorem ipsum",
        "translate": "надежда",
      },
      {
        "id": 71156751,
        "title": "Word",
        "word": "roof",
        "paragraph": "Lorem ipsum",
        "translate": "крыша",
      },
      {
        "id": 71156171,
        "title": "Word",
        "word": "pen",
        "paragraph": "Lorem ipsum",
        "translate": "ручка",
      },
      {
        "id": 91156151,
        "title": "Word",
        "word": "chair",
        "paragraph": "Lorem ipsum",
        "translate": "стул",
      },
      {
        "id": 21156151,
        "title": "Word",
        "word": "guitar",
        "paragraph": "Lorem ipsum",
        "translate": "гитара",
      },
      {
        "id": 33156100,
        "title": "Word",
        "word": "phone",
        "paragraph": "Lorem ipsum",
        "translate": "телефон",
      },
      {
        "id": 71165151,
        "title": "Word",
        "word": "laptop",
        "paragraph": "Lorem ipsum",
        "translate": "ноутбук",
      },
      {
        "id": 71156831,
        "title": "Word",
        "word": "keyboard",
        "paragraph": "Lorem ipsum",
        "translate": "клавиатура",
      },
      {
        "id": 71156841,
        "title": "Word",
        "word": "map",
        "paragraph": "Lorem ipsum",
        "translate": "карта",
      },
      {
        "id": 71156191,
        "title": "Word",
        "word": "pillow",
        "paragraph": "Lorem ipsum",
        "translate": "подушка",
      },
      {
        "id": 70156159,
        "title": "Word",
        "word": "pill",
        "paragraph": "Lorem ipsum",
        "translate": "таблетка",
      },{
        "id": 45156151,
        "title": "Word",
        "word": "price",
        "paragraph": "Lorem ipsum",
        "translate": "цена",
      },
      {
        "id": 54156151,
        "title": "Word",
        "word": "gift",
        "paragraph": "Lorem ipsum",
        "translate": "подарок",
      },
      {
        "id": 33156151,
        "title": "Word",
        "word": "discount",
        "paragraph": "Lorem ipsum",
        "translate": "скидка",
      },
      {
        "id": 13156151,
        "title": "Word",
        "word": "cocnut",
        "paragraph": "Lorem ipsum",
        "translate": "кокос",
      },
      {
        "id": 31156151,
        "title": "Word",
        "word": "fish",
        "paragraph": "Lorem ipsum",
        "translate": "рыба",
      },
      {
        "id": 31356151,
        "title": "Word",
        "word": "bear",
        "paragraph": "Lorem ipsum",
        "translate": "медведь",
      },{
        "id": 31456151,
        "title": "Word",
        "word": "weapon",
        "paragraph": "Lorem ipsum",
        "translate": "оружие",
      },
      {
        "id": 31556151,
        "title": "Word",
        "word": "mountain",
        "paragraph": "Lorem ipsum",
        "translate": "гора",
      },
      {
        "id": 31656151,
        "title": "Word",
        "word": "offshore",
        "paragraph": "Lorem ipsum",
        "translate": "шельф",
      },
      {
        "id": 31756151,
        "title": "Word",
        "word": "pipeline",
        "paragraph": "Lorem ipsum",
        "translate": "трубопровод",
      },
      
    ]
  }